DROP TABLE IF EXISTS EngagePost;
DROP TABLE IF EXISTS Comment;
DROP TABLE IF EXISTS Event;
DROP TABLE IF EXISTS UniquePostboardPost;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS PostBoard;
DROP TABLE IF EXISTS UCinfo;
DROP TABLE IF EXISTS USER;
